const fs = require('node:fs');
const assert = require('node:assert/strict');

const html = fs.readFileSync('tools/JD/data-analysis.html', 'utf8');

assert.match(html, /data-gross-margin-panel="gift">数据导入与核对<\/button>[\s\S]*data-gross-margin-panel="algorithm">毛保算法<\/button>[\s\S]*data-gross-margin-panel="dashboard">数据看板<\/button>[\s\S]*data-gross-margin-panel="filter">数据筛选<\/button>/, 'gross-margin tabs should follow the merged import workflow');
assert.match(html, /id="grossMarginGiftPane"[\s\S]*id="financeGiftRulesSection"/, 'gift rules should have an independent pane');
assert.doesNotMatch(html, /id="grossMarginImportPane"/, 'data import should be merged into the gift-rule workflow');
assert.match(html, /id="financeGiftManualPane"[\s\S]*id="financeGiftManualImportSlot"[\s\S]*>赠品规则录入</, 'manual mode should place import above rule entry');
assert.match(html, /id="inspectFinanceManualDataBtn"[\s\S]*id="clearFinanceManualDataBtn"[\s\S]*id="financeManualDataStatus"/, 'manual mode should expose a month-scoped data inspection and clear interface');
assert.match(html, /function inspectFinanceManualMonthData\(\)[\s\S]*legacyRuleCount[\s\S]*已确认已清空/, 'manual data inspection should identify legacy rules and confirm an empty month');
assert.match(html, /function clearFinanceManualMonthData\(\)[\s\S]*snapshot\.metrics[\s\S]*snapshot\.manualRules[\s\S]*financePendingOrderSessions = financePendingOrderSessions\.filter/, 'manual data clearing should remove month metrics, manual rules and matching temporary sessions');
assert.match(html, /id="financeGiftAutoPane"[\s\S]*id="financeGiftAutoImportSlot"[\s\S]*>赠品规则录入</, 'automatic mode should place import above rule entry');
assert.match(html, /var importSlot = mode === 'auto'[\s\S]*importSlot\.appendChild\(importSection\)/, 'the single importer should follow the selected rule mode');
assert.match(html, /id="financeGiftHideZeroSales"/, 'gift rules should allow zero-sales rows to be hidden');
assert.match(html, /mode === 'auto' \|\| !financeGiftHideZeroSales \|\| Number\(row\.financeSalesQty\) > 0/, 'zero-sales filtering should only affect manual mode');
assert.match(html, /当前模式下方的“赠品规则录入”检查配置/, 'matched preset dialog should direct users to the active mode');
assert.match(html, /id="grossMarginDashboardDatePickerField"/, 'dashboard should expose its own date range picker');
assert.match(html, /datePickers\.grossMarginDashboard \? datePickers\.grossMarginDashboard\.getRange\(\)/, 'dashboard rows should use the visible dashboard date range');
assert.match(html, /var date = range\.startDate/, 'gross-margin imports should use dates from workbook rows');
assert.match(html, /<script src="gross-margin-orders\.js"><\/script>/, 'order compaction module should load before the page logic');
assert.match(html, /key: 'orderId', label: '订单编号'[\s\S]*不长期保存订单编号/, 'gross-margin mapping should include transient order ids');
assert.match(html, /mapping-rule-label">当前毛保算法/, 'preset label should describe the current gross-margin algorithm');
assert.match(html, /id="grossMarginGiftPane"[\s\S]*data-finance-gift-mode="auto"[\s\S]*data-finance-gift-mode="manual"[\s\S]*id="financeGiftManualPane"[\s\S]*id="financeGiftAutoPane"/, 'gift rules should put automatic mode first while keeping separate panes');
assert.match(html, /id="financeGiftManualPane"[\s\S]*id="importFinanceGiftHistoryBtn"[\s\S]*id="financeGiftTable"[\s\S]*id="financeGiftAutoPane"[\s\S]*id="importPreviousFinanceAutoRulesBtn"[\s\S]*id="financeGiftAutoTable"/, 'manual history and automatic return-list tools should stay in their own panes');
assert.match(html, /function importPreviousFinanceAutoRules\(\)[\s\S]*rule\.ruleMode === 'auto'[\s\S]*请逐项检查后再点击/, 'automatic mode should import only the previous automatic return list and require review');
assert.match(html, /id="financeMissingSkuModal"[\s\S]*id="financeMissingSkuBody"[\s\S]*function showFinanceMissingSkuWarning\(skus\)[\s\S]*showFinanceMissingSkuWarning\(Object\.keys\(importedSkus\)/, 'unknown finance SKUs should be shown in a blocking reminder');
assert.doesNotMatch(html, /id="financeGiftDimBtn"|id="financeGiftDimPopover"|id="financeGiftDimTags"/, 'gift rules should use fixed series filters instead of duplicate dimension controls');
assert.match(html, /收入成本归还主品/, 'automatic mode should explain and expose return-to-main rules');
assert.match(html, /JDGrossMarginOrders\.createSession\(\)[\s\S]*orderIndex % 5000[\s\S]*replaceFinanceOrderGroups/, 'large imports should compact incrementally before persistence');
assert.match(html, /purchaseQty[\s\S]*returnQty[\s\S]*incomeAdjustment[\s\S]*costAdjustment[\s\S]*adjustedGrossMargin/, 'daily SKU metrics should preserve purchase, return and adjustment values');
assert.doesNotMatch(html, /put\([^\n]*orderId/, 'order ids must not be written to long-term stores');
assert.match(html, /id="financeGiftHistoryRange"/, 'history month selector should exist');
assert.match(html, /id="importFinanceGiftHistoryBtn"/, 'history import button should exist');
assert.match(html, /id="importFinanceGiftHistoryBtn"[^>]*>导入过往配置<\/button>[\s\S]*id="financeGiftHistoryRange"/, 'import button should appear before the plain-text range selector');
assert.match(html, /function importFinanceGiftHistory\(\)/, 'history import handler should exist');
assert.doesNotMatch(html, /rule\.sourceType === 'gift_accessory_rule' && rule\.startDate/, 'legacy rules without sourceType should remain importable');
assert.match(html, /return rule\.sku && rule\.startDate && rule\.endDate && rule\.endDate < query\.start;/, 'history ranges should not require non-empty accessory arrays');
assert.match(html, /row\.sourceType === 'finance_gross_margin' && row\.startDate/, 'imported finance months should also populate history choices');
assert.match(html, /rule\.startDate >= parts\[0\] && rule\.endDate <= parts\[1\]/, 'legacy rules within the selected month should be importable');
assert.match(html, /Number\(row\.financeSalesQty\) > 0 \|\| \(row\.accessories \|\| \[\]\)\.length \|\| \(row\.gifts \|\| \[\]\)\.length/, 'imported rules should remain visible without current-month finance data');

console.log('finance gift history checks passed');
